//
//  Language.swift
//  GoogleMapDirectionLib
//
//  Created by TriNgo on 5/12/20.
//  Copyright © 2020 RoverDream. All rights reserved.
//

import Foundation

public struct Language {
  
  public static let AFRIKAANS = "af"
  public static let ALBANIAN = "sq"
  public static let AMHARIC = "am"
  public static let ARABIC = "ar"
  public static let ARMENIAN = "hy"
  public static let AZERBAIJANI = "az"
  public static let BASQUE = "eu"
  public static let BELARUSIAN = "be"
  public static let BENGALI = "bn"
  public static let BOSNIAN = "bs"
  public static let BULGARIAN = "bg"
  public static let BURMESE = "my"
  public static let CATALAN = "ca"
  public static let CHINESE = "zh"
  public static let CHINESE_Simplified = "zh-CN"
  public static let CHINESE_HONG_KONG = "zh-HK"
  public static let CHINESE_TRADITIONAL = "zh-TW"
  public static let CROATIAN = "hr"
  public static let CZECH = "cs"
  public static let DANISH = "da"
  public static let DUTCH = "nl"
  public static let ENGLISH = "en"
  public static let ENGLISH_AUSTRALIAN = "en-AU"
  public static let ENGLISH_GREAT_BRITAIN = "en-GB"
  public static let ESTONIAN = "et"
  public static let FARSI = "fa"
  public static let FINNISH = "fi"
  public static let FILIPINO = "fil"
  public static let FRENCH = "fr"
  public static let FRENCH_CANADA = "fr-CA"
  public static let GALICIAN = "gl"
  public static let GEORGIAN = "ka"
  public static let GERMAN = "de"
  public static let GREEK = "el"
  public static let GUJARATI = "gu"
  public static let HEBREW = "iw"
  public static let HINDI = "hi"
  public static let HUNGARIAN = "hu"
  public static let ICELANDIC = "is"
  public static let INDONESIAN = "id"
  public static let ITALIAN = "it"
  public static let JAPANESE = "ja"
  public static let KANNADA = "kn"
  public static let KAZAKH = "kk"
  public static let KHMER = "km"
  public static let KOREAN = "ko"
  public static let KYRGYZ = "ky"
  public static let LAO = "lo"
  public static let LATVIAN = "lv"
  public static let LITHUANIAN = "lt"
  public static let MACEDONIAN = "mk"
  public static let MALAY = "ms"
  public static let MALAYALAM = "ml"
  public static let MARATHI = "mr"
  public static let MONGOLIAN = "mn"
  public static let NEPALI = "ne"
  public static let NORWEGIAN = "no"
  public static let POLISH = "pl"
  public static let PORTUGUESE = "pt"
  public static let PORTUGUESE_BRAZIL = "pt-BR"
  public static let PORTUGUESE_PORTUGAL = "pt-PT"
  public static let PUNJABI = "pa"
  public static let ROMANIAN = "rp"
  public static let RUSSIAN = "ru"
  public static let SERBIAN = "sr"
  public static let SINHALESE = "si"
  public static let SLOVAK = "sk"
  public static let SLOVENIAN = "sl"
  public static let SPANISH = "es"
  public static let SPANISH_LATIN_AMERICA = "es-419"
  public static let SWAHILI = "sw"
  public static let SWEDISH = "sv"
  public static let TAMIL = "ta"
  public static let TELUGU = "te"
  public static let THAI = "th"
  public static let TURKISH = "tr"
  public static let UKRAINIAN = "uk"
  public static let URDU = "ur"
  public static let UZBEK = "uz"
  public static let VIETNAMESE = "vi"
  public static let ZULU = "zu"
}
